python3 product_crawler.py -t "mẹ & bé" -c 3 -l "mongodb"
python3 product_crawler.py -t "nhà cửa & đời sống" -c 3 -l "mongodb"
python3 product_crawler.py -t "sách, vpp & âm nhạc" -c 3 -l "mongodb"
python3 product_crawler.py -t "sức khỏe & sắc đẹp" -c 3 -l "mongodb"
python3 product_crawler.py -t "thời trang" -c 3 -l "mongodb"
python3 product_crawler.py -t "thực phẩm" -c 3 -l "mongodb"
python3 product_crawler.py -t "voucher dịch vụ" -c 3 -l "mongodb"
python3 product_crawler.py -t "vé máy bay – dịch vụ" -c 3 -l "mongodb"
python3 product_crawler.py -t "điện máy & công nghệ" -c 3 -l "mongodb"
